name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  buildForWebGL:
    name: Build WebGL
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Cache
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-WebGL
          restore-keys: Library-

      - name: Unity Builder
        uses: game-ci/unity-builder@v3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: WebGL

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: deploy
          folder: build/WebGL/WebGL